name: Deploy to Dev

on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo systemctl restart dev_evolver.service
